// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appserve.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request 总体数据格式定义
type ClientComRequest struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Qid                  string      `protobuf:"bytes,2,opt,name=qid,proto3" json:"qid,omitempty"`
	TraceId              string      `protobuf:"bytes,3,opt,name=trace_id,proto3" json:"trace_id,omitempty"`
	MethodPath           *MethodPath `protobuf:"bytes,4,opt,name=method_path,json=methodPath,proto3" json:"method_path,omitempty"`
	FrontEnd             *FrontEnd   `protobuf:"bytes,5,opt,name=front_end,json=frontEnd,proto3" json:"front_end,omitempty"`
	Params               *any.Any    `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClientComRequest) Reset()         { *m = ClientComRequest{} }
func (m *ClientComRequest) String() string { return proto.CompactTextString(m) }
func (*ClientComRequest) ProtoMessage()    {}
func (*ClientComRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a4fb3df505b8368, []int{0}
}

func (m *ClientComRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientComRequest.Unmarshal(m, b)
}
func (m *ClientComRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientComRequest.Marshal(b, m, deterministic)
}
func (m *ClientComRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientComRequest.Merge(m, src)
}
func (m *ClientComRequest) XXX_Size() int {
	return xxx_messageInfo_ClientComRequest.Size(m)
}
func (m *ClientComRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientComRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientComRequest proto.InternalMessageInfo

func (m *ClientComRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientComRequest) GetQid() string {
	if m != nil {
		return m.Qid
	}
	return ""
}

func (m *ClientComRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *ClientComRequest) GetMethodPath() *MethodPath {
	if m != nil {
		return m.MethodPath
	}
	return nil
}

func (m *ClientComRequest) GetFrontEnd() *FrontEnd {
	if m != nil {
		return m.FrontEnd
	}
	return nil
}

func (m *ClientComRequest) GetParams() *any.Any {
	if m != nil {
		return m.Params
	}
	return nil
}

//方法路径
type MethodPath struct {
	Resource             string   `protobuf:"bytes,1,opt,name=resource,json=res,proto3" json:"resource,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,json=act,proto3" json:"action,omitempty"`
	Revision             string   `protobuf:"bytes,3,opt,name=revision,json=rev,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodPath) Reset()         { *m = MethodPath{} }
func (m *MethodPath) String() string { return proto.CompactTextString(m) }
func (*MethodPath) ProtoMessage()    {}
func (*MethodPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a4fb3df505b8368, []int{1}
}

func (m *MethodPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodPath.Unmarshal(m, b)
}
func (m *MethodPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodPath.Marshal(b, m, deterministic)
}
func (m *MethodPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodPath.Merge(m, src)
}
func (m *MethodPath) XXX_Size() int {
	return xxx_messageInfo_MethodPath.Size(m)
}
func (m *MethodPath) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodPath.DiscardUnknown(m)
}

var xxx_messageInfo_MethodPath proto.InternalMessageInfo

func (m *MethodPath) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *MethodPath) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MethodPath) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

//前端参数，定稿参数就要等待定稿
type FrontEnd struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ClientVersion        string   `protobuf:"bytes,3,opt,name=client_version,json=cver,proto3" json:"client_version,omitempty"`
	Platform             string   `protobuf:"bytes,4,opt,name=platform,json=platf,proto3" json:"platform,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            string   `protobuf:"bytes,6,opt,name=signature,json=sig,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrontEnd) Reset()         { *m = FrontEnd{} }
func (m *FrontEnd) String() string { return proto.CompactTextString(m) }
func (*FrontEnd) ProtoMessage()    {}
func (*FrontEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a4fb3df505b8368, []int{2}
}

func (m *FrontEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrontEnd.Unmarshal(m, b)
}
func (m *FrontEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrontEnd.Marshal(b, m, deterministic)
}
func (m *FrontEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrontEnd.Merge(m, src)
}
func (m *FrontEnd) XXX_Size() int {
	return xxx_messageInfo_FrontEnd.Size(m)
}
func (m *FrontEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_FrontEnd.DiscardUnknown(m)
}

var xxx_messageInfo_FrontEnd proto.InternalMessageInfo

func (m *FrontEnd) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FrontEnd) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *FrontEnd) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *FrontEnd) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *FrontEnd) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *FrontEnd) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// ServerComResponse 统一接入响应手机端的数据结构
type ServerComResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	TraceId              string   `protobuf:"bytes,4,opt,name=trace_id,proto3" json:"trace_id,omitempty"`
	SeqId                string   `protobuf:"bytes,5,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Ts                   int64    `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`
	Header               *any.Any `protobuf:"bytes,7,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *any.Any `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerComResponse) Reset()         { *m = ServerComResponse{} }
func (m *ServerComResponse) String() string { return proto.CompactTextString(m) }
func (*ServerComResponse) ProtoMessage()    {}
func (*ServerComResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a4fb3df505b8368, []int{3}
}

func (m *ServerComResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerComResponse.Unmarshal(m, b)
}
func (m *ServerComResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerComResponse.Marshal(b, m, deterministic)
}
func (m *ServerComResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerComResponse.Merge(m, src)
}
func (m *ServerComResponse) XXX_Size() int {
	return xxx_messageInfo_ServerComResponse.Size(m)
}
func (m *ServerComResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerComResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerComResponse proto.InternalMessageInfo

func (m *ServerComResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServerComResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ServerComResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ServerComResponse) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *ServerComResponse) GetSeqId() string {
	if m != nil {
		return m.SeqId
	}
	return ""
}

func (m *ServerComResponse) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *ServerComResponse) GetHeader() *any.Any {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ServerComResponse) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientComRequest)(nil), "main.ClientComRequest")
	proto.RegisterType((*MethodPath)(nil), "main.MethodPath")
	proto.RegisterType((*FrontEnd)(nil), "main.FrontEnd")
	proto.RegisterType((*ServerComResponse)(nil), "main.ServerComResponse")
}

func init() { proto.RegisterFile("appserve.proto", fileDescriptor_2a4fb3df505b8368) }

var fileDescriptor_2a4fb3df505b8368 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x9a, 0xb4, 0x4b, 0xee, 0x44, 0x55, 0x0c, 0xdb, 0x42, 0xc5, 0xc3, 0xd4, 0xa7, 0x4a,
	0xa0, 0x4c, 0x8c, 0x37, 0xde, 0xa6, 0x89, 0x49, 0x3c, 0x20, 0x90, 0xf9, 0x80, 0xca, 0x8d, 0x6f,
	0x1b, 0x6b, 0x8d, 0x9d, 0xda, 0x4e, 0x45, 0xbf, 0x83, 0xff, 0xe3, 0x91, 0xef, 0x40, 0xbe, 0x69,
	0x0a, 0xdb, 0xa4, 0xbd, 0x1d, 0x1f, 0x1f, 0x5f, 0xdf, 0x7b, 0xce, 0x85, 0xb1, 0x68, 0x1a, 0x87,
	0x76, 0x87, 0x45, 0x63, 0x8d, 0x37, 0x2c, 0xa9, 0x85, 0xd2, 0xd3, 0x37, 0x6b, 0x63, 0xd6, 0x1b,
	0xbc, 0x22, 0x6e, 0xd9, 0xae, 0xae, 0x84, 0xde, 0x77, 0x82, 0xd9, 0xef, 0x08, 0x26, 0xb7, 0x1b,
	0x85, 0xda, 0xdf, 0x9a, 0x9a, 0xe3, 0xb6, 0x45, 0xe7, 0xd9, 0x18, 0x06, 0x4a, 0xe6, 0xd1, 0x65,
	0x34, 0xcf, 0xf8, 0x40, 0x49, 0x36, 0x81, 0x78, 0xab, 0x64, 0x3e, 0x20, 0x22, 0x40, 0x36, 0x85,
	0xd4, 0x5b, 0x51, 0xe2, 0x42, 0xc9, 0x3c, 0x26, 0xfa, 0x78, 0x66, 0x1f, 0xe0, 0xb4, 0x46, 0x5f,
	0x19, 0xb9, 0x68, 0x84, 0xaf, 0xf2, 0xe4, 0x32, 0x9a, 0x9f, 0x5e, 0x4f, 0x8a, 0xd0, 0x49, 0xf1,
	0x95, 0x2e, 0xbe, 0x0b, 0x5f, 0x71, 0xa8, 0x8f, 0x98, 0xbd, 0x83, 0x6c, 0x65, 0x8d, 0xf6, 0x0b,
	0xd4, 0x32, 0x1f, 0xd2, 0x83, 0x71, 0xf7, 0xe0, 0x2e, 0xd0, 0x9f, 0xb5, 0xe4, 0xe9, 0xea, 0x80,
	0xd8, 0x7b, 0x18, 0x35, 0xc2, 0x8a, 0xda, 0xe5, 0x23, 0x52, 0xbe, 0x2e, 0xba, 0xf1, 0x8a, 0x7e,
	0xbc, 0xe2, 0x46, 0xef, 0xf9, 0x41, 0x33, 0xfb, 0x06, 0xf0, 0xef, 0x53, 0x76, 0x06, 0xa9, 0x45,
	0x67, 0x5a, 0x5b, 0xe2, 0x61, 0xbe, 0xd8, 0xa2, 0x63, 0xaf, 0x60, 0x24, 0x4a, 0xaf, 0x8c, 0xee,
	0x67, 0x14, 0xa5, 0xef, 0xb4, 0x3b, 0xe5, 0x02, 0x1d, 0xf7, 0xda, 0xdd, 0xec, 0x57, 0x04, 0x69,
	0xdf, 0x55, 0x70, 0xe6, 0x1e, 0xf7, 0x7d, 0xa9, 0x7b, 0xdc, 0x33, 0x06, 0x49, 0xdb, 0x1e, 0xcd,
	0x22, 0xcc, 0xde, 0xc2, 0xb8, 0x24, 0x8f, 0x17, 0x3b, 0xb4, 0xff, 0xd5, 0x4b, 0xca, 0x1d, 0x5a,
	0x76, 0x01, 0x69, 0xb3, 0x11, 0x7e, 0x65, 0x6c, 0x4d, 0x66, 0x65, 0x7c, 0x48, 0xe7, 0x50, 0xaa,
	0x12, 0xae, 0x22, 0x43, 0x32, 0x4e, 0x98, 0x9d, 0x43, 0xe6, 0xd4, 0x5a, 0x0b, 0xdf, 0x5a, 0xa4,
	0xf9, 0x33, 0x1e, 0x3b, 0xb5, 0x9e, 0xfd, 0x89, 0xe0, 0xe5, 0x8f, 0x10, 0xbc, 0xa5, 0x1c, 0x5d,
	0x63, 0xb4, 0xc3, 0x27, 0x41, 0x32, 0x48, 0x4a, 0x23, 0x91, 0x9a, 0x7b, 0xc1, 0x09, 0x07, 0xce,
	0xe3, 0x4f, 0xdf, 0xb7, 0x14, 0xf0, 0x83, 0x78, 0x93, 0x47, 0xf1, 0x9e, 0xc1, 0xc8, 0xe1, 0x36,
	0xdc, 0x74, 0x7d, 0x0d, 0x1d, 0x6e, 0xbf, 0xc8, 0xf0, 0x95, 0xef, 0x12, 0x89, 0xf9, 0xc0, 0xbb,
	0x90, 0x52, 0x85, 0x42, 0xa2, 0xcd, 0x4f, 0x9e, 0x4b, 0xa9, 0xd3, 0xb0, 0x39, 0x24, 0x4b, 0x23,
	0xf7, 0x79, 0xfa, 0x8c, 0x96, 0x14, 0xd7, 0x77, 0x90, 0xde, 0x34, 0x0d, 0x8d, 0xca, 0x3e, 0xc1,
	0x49, 0xbf, 0xb2, 0xe7, 0xdd, 0xba, 0x3c, 0x5e, 0xe5, 0xe9, 0x45, 0xc7, 0x3f, 0xb1, 0x66, 0x39,
	0xa2, 0xda, 0x1f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xd8, 0x2d, 0x59, 0x32, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppServeClient is the client API for AppServe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppServeClient interface {
	Request(ctx context.Context, in *ClientComRequest, opts ...grpc.CallOption) (*ServerComResponse, error)
}

type appServeClient struct {
	cc *grpc.ClientConn
}

func NewAppServeClient(cc *grpc.ClientConn) AppServeClient {
	return &appServeClient{cc}
}

func (c *appServeClient) Request(ctx context.Context, in *ClientComRequest, opts ...grpc.CallOption) (*ServerComResponse, error) {
	out := new(ServerComResponse)
	err := c.cc.Invoke(ctx, "/main.AppServe/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServeServer is the server API for AppServe service.
type AppServeServer interface {
	Request(context.Context, *ClientComRequest) (*ServerComResponse, error)
}

// UnimplementedAppServeServer can be embedded to have forward compatible implementations.
type UnimplementedAppServeServer struct {
}

func (*UnimplementedAppServeServer) Request(ctx context.Context, req *ClientComRequest) (*ServerComResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}

func RegisterAppServeServer(s *grpc.Server, srv AppServeServer) {
	s.RegisterService(&_AppServe_serviceDesc, srv)
}

func _AppServe_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientComRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServeServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AppServe/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServeServer).Request(ctx, req.(*ClientComRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppServe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.AppServe",
	HandlerType: (*AppServeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _AppServe_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appserve.proto",
}
