// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appserve.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request 总体数据格式定义
type ClientComRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Qid                  string         `protobuf:"bytes,2,opt,name=qid,proto3" json:"qid,omitempty"`
	TraceId              string         `protobuf:"bytes,3,opt,name=trace_id,proto3" json:"trace_id,omitempty"`
	Meta                 *ClientComMeta `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Params               *any.Any       `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ClientComRequest) Reset()         { *m = ClientComRequest{} }
func (m *ClientComRequest) String() string { return proto.CompactTextString(m) }
func (*ClientComRequest) ProtoMessage()    {}
func (*ClientComRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a4fb3df505b8368, []int{0}
}

func (m *ClientComRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientComRequest.Unmarshal(m, b)
}
func (m *ClientComRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientComRequest.Marshal(b, m, deterministic)
}
func (m *ClientComRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientComRequest.Merge(m, src)
}
func (m *ClientComRequest) XXX_Size() int {
	return xxx_messageInfo_ClientComRequest.Size(m)
}
func (m *ClientComRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientComRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientComRequest proto.InternalMessageInfo

func (m *ClientComRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientComRequest) GetQid() string {
	if m != nil {
		return m.Qid
	}
	return ""
}

func (m *ClientComRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *ClientComRequest) GetMeta() *ClientComMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ClientComRequest) GetParams() *any.Any {
	if m != nil {
		return m.Params
	}
	return nil
}

// Meta 统一接入请求解析参数集合，统一接入会解析其中的值，根据值将请求发送给相关的后端APP
type ClientComMeta struct {
	Resource             string   `protobuf:"bytes,1,opt,name=resource,json=res,proto3" json:"resource,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=action,json=act,proto3" json:"action,omitempty"`
	Revision             string   `protobuf:"bytes,3,opt,name=revision,json=rev,proto3" json:"revision,omitempty"`
	Subscription         bool     `protobuf:"varint,4,opt,name=subscription,json=sub,proto3" json:"subscription,omitempty"`
	Key                  string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Uuid                 string   `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ClientVersion        string   `protobuf:"bytes,7,opt,name=client_version,json=cver,proto3" json:"client_version,omitempty"`
	Platform             string   `protobuf:"bytes,8,opt,name=platform,json=platf,proto3" json:"platform,omitempty"`
	Hash                 string   `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature            string   `protobuf:"bytes,10,opt,name=signature,json=sig,proto3" json:"signature,omitempty"`
	Params               *any.Any `protobuf:"bytes,11,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientComMeta) Reset()         { *m = ClientComMeta{} }
func (m *ClientComMeta) String() string { return proto.CompactTextString(m) }
func (*ClientComMeta) ProtoMessage()    {}
func (*ClientComMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a4fb3df505b8368, []int{1}
}

func (m *ClientComMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientComMeta.Unmarshal(m, b)
}
func (m *ClientComMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientComMeta.Marshal(b, m, deterministic)
}
func (m *ClientComMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientComMeta.Merge(m, src)
}
func (m *ClientComMeta) XXX_Size() int {
	return xxx_messageInfo_ClientComMeta.Size(m)
}
func (m *ClientComMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientComMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ClientComMeta proto.InternalMessageInfo

func (m *ClientComMeta) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *ClientComMeta) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ClientComMeta) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ClientComMeta) GetSubscription() bool {
	if m != nil {
		return m.Subscription
	}
	return false
}

func (m *ClientComMeta) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ClientComMeta) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ClientComMeta) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *ClientComMeta) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *ClientComMeta) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *ClientComMeta) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ClientComMeta) GetParams() *any.Any {
	if m != nil {
		return m.Params
	}
	return nil
}

// ServerComResponse 统一接入响应手机端的数据结构
type ServerComResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	TraceId              string   `protobuf:"bytes,4,opt,name=trace_id,proto3" json:"trace_id,omitempty"`
	SeqId                string   `protobuf:"bytes,5,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Ts                   int64    `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`
	Header               *any.Any `protobuf:"bytes,7,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *any.Any `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerComResponse) Reset()         { *m = ServerComResponse{} }
func (m *ServerComResponse) String() string { return proto.CompactTextString(m) }
func (*ServerComResponse) ProtoMessage()    {}
func (*ServerComResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a4fb3df505b8368, []int{2}
}

func (m *ServerComResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerComResponse.Unmarshal(m, b)
}
func (m *ServerComResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerComResponse.Marshal(b, m, deterministic)
}
func (m *ServerComResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerComResponse.Merge(m, src)
}
func (m *ServerComResponse) XXX_Size() int {
	return xxx_messageInfo_ServerComResponse.Size(m)
}
func (m *ServerComResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerComResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerComResponse proto.InternalMessageInfo

func (m *ServerComResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServerComResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ServerComResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ServerComResponse) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *ServerComResponse) GetSeqId() string {
	if m != nil {
		return m.SeqId
	}
	return ""
}

func (m *ServerComResponse) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *ServerComResponse) GetHeader() *any.Any {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ServerComResponse) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientComRequest)(nil), "pb.ClientComRequest")
	proto.RegisterType((*ClientComMeta)(nil), "pb.ClientComMeta")
	proto.RegisterType((*ServerComResponse)(nil), "pb.ServerComResponse")
}

func init() { proto.RegisterFile("appserve.proto", fileDescriptor_2a4fb3df505b8368) }

var fileDescriptor_2a4fb3df505b8368 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xd5, 0x7e, 0x64, 0xbb, 0x99, 0xd2, 0xa8, 0x35, 0x0d, 0x6c, 0x23, 0x0e, 0x55, 0x25, 0xa4,
	0x1c, 0xd0, 0x56, 0x2a, 0x12, 0xf7, 0xd2, 0x13, 0x07, 0x2e, 0xcb, 0x0f, 0xa8, 0xbc, 0xeb, 0x69,
	0x62, 0x91, 0xac, 0x1d, 0x8f, 0x77, 0x45, 0xfe, 0x0f, 0xfc, 0x35, 0x7e, 0x07, 0xf2, 0x6c, 0x52,
	0x11, 0xaa, 0x48, 0xdc, 0x9e, 0xdf, 0x3c, 0xcf, 0x3c, 0xbf, 0x31, 0x4c, 0xa4, 0xb5, 0x84, 0xae,
	0xc7, 0xd2, 0x3a, 0xe3, 0x8d, 0x88, 0x6d, 0x3d, 0xbb, 0x5a, 0x18, 0xb3, 0x58, 0xe1, 0x2d, 0x33,
	0x75, 0xf7, 0x74, 0x2b, 0xdb, 0xed, 0x50, 0xbe, 0xf9, 0x15, 0xc1, 0xf9, 0xc3, 0x4a, 0x63, 0xeb,
	0x1f, 0xcc, 0xba, 0xc2, 0x4d, 0x87, 0xe4, 0xc5, 0x04, 0x62, 0xad, 0x8a, 0xe8, 0x3a, 0x9a, 0x8f,
	0xab, 0x58, 0x2b, 0x71, 0x0e, 0xc9, 0x46, 0xab, 0x22, 0x66, 0x22, 0x40, 0x31, 0x83, 0xdc, 0x3b,
	0xd9, 0xe0, 0xa3, 0x56, 0x45, 0xc2, 0xf4, 0xf3, 0x59, 0xbc, 0x87, 0x74, 0x8d, 0x5e, 0x16, 0xe9,
	0x75, 0x34, 0x3f, 0xbd, 0xbb, 0x28, 0x6d, 0x5d, 0x3e, 0x4f, 0xf8, 0x8a, 0x5e, 0x56, 0x5c, 0x16,
	0x1f, 0x20, 0xb3, 0xd2, 0xc9, 0x35, 0x15, 0x23, 0x16, 0x5e, 0x96, 0x83, 0xcb, 0x72, 0xef, 0xb2,
	0xbc, 0x6f, 0xb7, 0xd5, 0x4e, 0x73, 0xf3, 0x33, 0x86, 0xb3, 0x83, 0x2e, 0x62, 0x0a, 0xb9, 0x43,
	0x32, 0x9d, 0x6b, 0x70, 0x67, 0x35, 0x71, 0x48, 0xe2, 0x35, 0x64, 0xb2, 0xf1, 0xda, 0xb4, 0x7b,
	0xbb, 0xb2, 0xf1, 0x83, 0xb6, 0xd7, 0x14, 0xe8, 0x64, 0xaf, 0xed, 0xc5, 0x15, 0xbc, 0xa2, 0xae,
	0xa6, 0xc6, 0x69, 0xcb, 0x37, 0x82, 0xe3, 0xbc, 0x4a, 0xa8, 0xab, 0xc3, 0x93, 0xbf, 0xe3, 0x96,
	0xad, 0x8d, 0xab, 0x00, 0x85, 0x80, 0xb4, 0xeb, 0xb4, 0x2a, 0x32, 0xa6, 0x18, 0x8b, 0x77, 0x30,
	0x69, 0xd8, 0xd4, 0x63, 0x8f, 0x8e, 0xbb, 0x9f, 0x0c, 0xd5, 0xa6, 0x47, 0x27, 0xde, 0x42, 0x6e,
	0x57, 0xd2, 0x3f, 0x19, 0xb7, 0x2e, 0x72, 0xe6, 0x47, 0x7c, 0x0e, 0xad, 0x96, 0x92, 0x96, 0xc5,
	0x78, 0x10, 0x07, 0x2c, 0xde, 0xc0, 0x98, 0xf4, 0xa2, 0x95, 0xbe, 0x73, 0x58, 0xc0, 0x30, 0x96,
	0xf4, 0xe2, 0xaf, 0x98, 0x4e, 0xff, 0x23, 0xa6, 0xdf, 0x11, 0x5c, 0x7c, 0x0b, 0xdb, 0x77, 0xbc,
	0x4e, 0xb2, 0xa6, 0x25, 0x7c, 0xb1, 0x4f, 0x01, 0x69, 0x63, 0x14, 0x72, 0x42, 0x67, 0x15, 0xe3,
	0xc0, 0x79, 0xfc, 0xe1, 0x77, 0xf1, 0x30, 0x3e, 0xd8, 0x72, 0xfa, 0xcf, 0x96, 0xa7, 0x90, 0x11,
	0x6e, 0x42, 0x65, 0xc8, 0x68, 0x44, 0xb8, 0xf9, 0xa2, 0xc2, 0x28, 0x4f, 0x9c, 0x51, 0x52, 0xc5,
	0x9e, 0x82, 0xfd, 0x25, 0x4a, 0x85, 0x8e, 0x93, 0x39, 0x6a, 0x7f, 0xd0, 0x88, 0x39, 0xa4, 0xb5,
	0x51, 0x5b, 0x4e, 0xeb, 0x98, 0x96, 0x15, 0x77, 0x9f, 0x21, 0xbf, 0xb7, 0x96, 0x9f, 0x2a, 0x3e,
	0xc1, 0xc9, 0xfe, 0xe7, 0x5e, 0x1e, 0xfc, 0xb6, 0x1d, 0x3b, 0x9b, 0x06, 0xf6, 0x45, 0x2c, 0x75,
	0xc6, 0x7d, 0x3f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x53, 0x6a, 0x3d, 0x33, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppServeClient is the client API for AppServe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppServeClient interface {
	Request(ctx context.Context, in *ClientComRequest, opts ...grpc.CallOption) (*ServerComResponse, error)
}

type appServeClient struct {
	cc *grpc.ClientConn
}

func NewAppServeClient(cc *grpc.ClientConn) AppServeClient {
	return &appServeClient{cc}
}

func (c *appServeClient) Request(ctx context.Context, in *ClientComRequest, opts ...grpc.CallOption) (*ServerComResponse, error) {
	out := new(ServerComResponse)
	err := c.cc.Invoke(ctx, "/pb.AppServe/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServeServer is the server API for AppServe service.
type AppServeServer interface {
	Request(context.Context, *ClientComRequest) (*ServerComResponse, error)
}

func RegisterAppServeServer(s *grpc.Server, srv AppServeServer) {
	s.RegisterService(&_AppServe_serviceDesc, srv)
}

func _AppServe_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientComRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServeServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AppServe/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServeServer).Request(ctx, req.(*ClientComRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppServe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AppServe",
	HandlerType: (*AppServeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _AppServe_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appserve.proto",
}
