// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package eventbus

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Original             string   `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

type ResponseHeader struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

type Request struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *any.Any       `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type GatewayComMessage struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Seq                  int64          `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	From                 string         `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Topic                string         `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *any.Any       `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GatewayComMessage) Reset()         { *m = GatewayComMessage{} }
func (m *GatewayComMessage) String() string { return proto.CompactTextString(m) }
func (*GatewayComMessage) ProtoMessage()    {}
func (*GatewayComMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GatewayComMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayComMessage.Unmarshal(m, b)
}
func (m *GatewayComMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayComMessage.Marshal(b, m, deterministic)
}
func (m *GatewayComMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayComMessage.Merge(m, src)
}
func (m *GatewayComMessage) XXX_Size() int {
	return xxx_messageInfo_GatewayComMessage.Size(m)
}
func (m *GatewayComMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayComMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayComMessage proto.InternalMessageInfo

func (m *GatewayComMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GatewayComMessage) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *GatewayComMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GatewayComMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GatewayComMessage) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GatewayComMessage) GetBody() *any.Any {
	if m != nil {
		return m.Body
	}
	return nil
}

type AppComMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppComMessage) Reset()         { *m = AppComMessage{} }
func (m *AppComMessage) String() string { return proto.CompactTextString(m) }
func (*AppComMessage) ProtoMessage()    {}
func (*AppComMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *AppComMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppComMessage.Unmarshal(m, b)
}
func (m *AppComMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppComMessage.Marshal(b, m, deterministic)
}
func (m *AppComMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppComMessage.Merge(m, src)
}
func (m *AppComMessage) XXX_Size() int {
	return xxx_messageInfo_AppComMessage.Size(m)
}
func (m *AppComMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AppComMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AppComMessage proto.InternalMessageInfo

type Response struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result               *any.Any        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetResult() *any.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

type AppInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Topics               []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppInfo) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

type RegReply struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegReply) Reset()         { *m = RegReply{} }
func (m *RegReply) String() string { return proto.CompactTextString(m) }
func (*RegReply) ProtoMessage()    {}
func (*RegReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *RegReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegReply.Unmarshal(m, b)
}
func (m *RegReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegReply.Marshal(b, m, deterministic)
}
func (m *RegReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegReply.Merge(m, src)
}
func (m *RegReply) XXX_Size() int {
	return xxx_messageInfo_RegReply.Size(m)
}
func (m *RegReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegReply proto.InternalMessageInfo

func (m *RegReply) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *RegReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegReply) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "eventbus.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "eventbus.ResponseHeader")
	proto.RegisterType((*Request)(nil), "eventbus.Request")
	proto.RegisterType((*GatewayComMessage)(nil), "eventbus.GatewayComMessage")
	proto.RegisterType((*AppComMessage)(nil), "eventbus.AppComMessage")
	proto.RegisterType((*Response)(nil), "eventbus.Response")
	proto.RegisterType((*AppInfo)(nil), "eventbus.AppInfo")
	proto.RegisterType((*RegReply)(nil), "eventbus.RegReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x95, 0x4d, 0x36, 0x4d, 0x07, 0x6d, 0x69, 0xad, 0x8a, 0x86, 0x70, 0xa9, 0x72, 0x8a,
	0x04, 0xca, 0x96, 0x22, 0xee, 0x2c, 0x1c, 0x80, 0x03, 0x1c, 0xfc, 0x06, 0x4e, 0x32, 0x1b, 0x8c,
	0xb2, 0xb1, 0x6b, 0x3b, 0x85, 0xf0, 0x68, 0x3c, 0x1d, 0x8a, 0xe3, 0x6c, 0x52, 0x90, 0x40, 0xdc,
	0x66, 0xc6, 0xbf, 0xfd, 0xff, 0xf3, 0xc9, 0xb0, 0xd1, 0xa8, 0xee, 0x79, 0x89, 0xb9, 0x54, 0xc2,
	0x08, 0x12, 0xe1, 0x3d, 0xb6, 0xa6, 0xe8, 0x74, 0xf2, 0xb4, 0x16, 0xa2, 0x6e, 0x70, 0x6b, 0xe7,
	0x45, 0xb7, 0xdf, 0xb2, 0xb6, 0x1f, 0x45, 0xe9, 0x73, 0xd8, 0x50, 0xbc, 0xeb, 0x50, 0x9b, 0x0f,
	0xc8, 0x2a, 0x54, 0x24, 0x81, 0x48, 0x28, 0x5e, 0xf3, 0x96, 0x35, 0xb1, 0x77, 0xed, 0x65, 0xa7,
	0xf4, 0xd8, 0xa7, 0xe7, 0x70, 0x46, 0x51, 0x4b, 0xd1, 0x6a, 0x1c, 0xd5, 0x69, 0x05, 0x27, 0xee,
	0x3a, 0xd9, 0x42, 0xf8, 0xc5, 0x0e, 0xed, 0xb5, 0x47, 0xb7, 0x57, 0xf9, 0xe4, 0x9f, 0x3f, 0x70,
	0xa0, 0x4e, 0x46, 0x32, 0x08, 0x0a, 0x51, 0xf5, 0xf1, 0xca, 0xca, 0x2f, 0xf3, 0x31, 0x64, 0x3e,
	0x85, 0xcc, 0x77, 0x6d, 0x4f, 0xad, 0x22, 0xfd, 0xe9, 0xc1, 0xc5, 0x7b, 0x66, 0xf0, 0x1b, 0xeb,
	0xdf, 0x89, 0xc3, 0x27, 0xd4, 0x9a, 0xd5, 0x48, 0xce, 0x60, 0xc5, 0x2b, 0x97, 0x71, 0xc5, 0x2b,
	0x72, 0x0e, 0xbe, 0xc6, 0x3b, 0xfb, 0x9c, 0x4f, 0x87, 0x92, 0x10, 0x08, 0xf6, 0x4a, 0x1c, 0x62,
	0xdf, 0x6a, 0x6c, 0x4d, 0x2e, 0x61, 0x6d, 0x84, 0xe4, 0x65, 0x1c, 0xd8, 0xe1, 0xd8, 0x2c, 0xc2,
	0xaf, 0xff, 0x2f, 0x7c, 0xf8, 0xcf, 0xf0, 0x8f, 0x61, 0xb3, 0x93, 0x72, 0xce, 0x9d, 0x7e, 0x85,
	0x68, 0xa2, 0x48, 0x6e, 0x7e, 0x83, 0x16, 0x2f, 0x7d, 0x97, 0xa4, 0x8f, 0xc6, 0x2f, 0x20, 0x54,
	0xa8, 0xbb, 0xc6, 0xfc, 0x95, 0x9b, 0xd3, 0xa4, 0xaf, 0xe1, 0x64, 0x27, 0xe5, 0xc7, 0x76, 0x2f,
	0x06, 0x18, 0x2d, 0x3b, 0xa0, 0x03, 0x66, 0x6b, 0xf2, 0x04, 0x42, 0xbb, 0xbf, 0x8e, 0x57, 0xd7,
	0x7e, 0x76, 0x4a, 0x5d, 0x97, 0x7e, 0x1e, 0x22, 0xd6, 0x14, 0x65, 0xd3, 0x0f, 0x1f, 0x82, 0x95,
	0x25, 0x4a, 0x83, 0x23, 0xec, 0x88, 0x1e, 0xfb, 0xe1, 0xcd, 0x52, 0x54, 0x68, 0xa3, 0xac, 0xa9,
	0xad, 0x87, 0x99, 0xc1, 0xef, 0x66, 0x82, 0x3e, 0xd4, 0xb7, 0x3f, 0xc0, 0x7f, 0xdb, 0x69, 0xf2,
	0x12, 0x22, 0x85, 0x35, 0xd7, 0x06, 0x15, 0xb9, 0x98, 0x37, 0x75, 0x09, 0x13, 0xb2, 0x5c, 0xde,
	0xb9, 0xbf, 0x81, 0x40, 0x72, 0x89, 0xe4, 0xea, 0x81, 0x7c, 0xa6, 0x99, 0x3c, 0x9b, 0x0f, 0xfe,
	0xf8, 0x22, 0x99, 0x77, 0xe3, 0x15, 0xa1, 0x05, 0xf3, 0xea, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x98, 0xe9, 0xb9, 0x93, 0x1e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BusClient is the client API for Bus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusClient interface {
	// APP向event bug 注册
	Register(ctx context.Context, in *AppInfo, opts ...grpc.CallOption) (*RegReply, error)
	Pipe(ctx context.Context, opts ...grpc.CallOption) (Bus_PipeClient, error)
}

type busClient struct {
	cc *grpc.ClientConn
}

func NewBusClient(cc *grpc.ClientConn) BusClient {
	return &busClient{cc}
}

func (c *busClient) Register(ctx context.Context, in *AppInfo, opts ...grpc.CallOption) (*RegReply, error) {
	out := new(RegReply)
	err := c.cc.Invoke(ctx, "/eventbus.Bus/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *busClient) Pipe(ctx context.Context, opts ...grpc.CallOption) (Bus_PipeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Bus_serviceDesc.Streams[0], "/eventbus.Bus/pipe", opts...)
	if err != nil {
		return nil, err
	}
	x := &busPipeClient{stream}
	return x, nil
}

type Bus_PipeClient interface {
	Send(*AppComMessage) error
	Recv() (*GatewayComMessage, error)
	grpc.ClientStream
}

type busPipeClient struct {
	grpc.ClientStream
}

func (x *busPipeClient) Send(m *AppComMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *busPipeClient) Recv() (*GatewayComMessage, error) {
	m := new(GatewayComMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BusServer is the server API for Bus service.
type BusServer interface {
	// APP向event bug 注册
	Register(context.Context, *AppInfo) (*RegReply, error)
	Pipe(Bus_PipeServer) error
}

func RegisterBusServer(s *grpc.Server, srv BusServer) {
	s.RegisterService(&_Bus_serviceDesc, srv)
}

func _Bus_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eventbus.Bus/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusServer).Register(ctx, req.(*AppInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bus_Pipe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BusServer).Pipe(&busPipeServer{stream})
}

type Bus_PipeServer interface {
	Send(*GatewayComMessage) error
	Recv() (*AppComMessage, error)
	grpc.ServerStream
}

type busPipeServer struct {
	grpc.ServerStream
}

func (x *busPipeServer) Send(m *GatewayComMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *busPipeServer) Recv() (*AppComMessage, error) {
	m := new(AppComMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Bus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eventbus.Bus",
	HandlerType: (*BusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register",
			Handler:    _Bus_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "pipe",
			Handler:       _Bus_Pipe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
